{% set version = "0.5.4" %}

package:
  name: symfit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/symfit/symfit-{{ version }}.tar.gz
  sha256: 9d74340144dc68f3c7870dc6adb44cd18070021e5804b30e142cd0ab35bb3d26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - python >=3.6
    - pip
    - pbr >=1.9
  run:
    - python >=3.6
    - numpy >=1.12
    - scipy >=1.0
    - sympy >=1.2
    - six
    - toposort
    - setuptools
    
test:
  imports:
    - symfit

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symbolic Fitting; fitting as it should be.
  doc_url: http://symfit.readthedocs.org
  dev_url: https://github.com/tBuLi/symfit

extra:
  recipe-maintainers:
    - tbuli
    - jhsmit
